# Generated by Django 5.2.4 on 2025-09-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbc_app', '0004_intentohoneypot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('count', models.IntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
